version: '3.3'

x-common-settings: &common-settings
  image: seocahill/patroni:1.2.5
  secrets: 
    - patroni.yml
  env_file:
    - test.env
  networks:
    - dbs
  entrypoint: patroni
  command: /run/secrets/patroni.yml

services:

  haproxy:
    image: haproxy:alpine
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8008:8008"
    configs: 
      - haproxy_cfg
    networks:
      - dbs
    command: haproxy -f /haproxy_cfg
  
  etcd:
    image: quay.io/coreos/etcd:v3.1.2
    configs:
      - etcd_cfg
    networks: 
      - dbs
    command: /bin/sh /etcd_cfg

  dbnode1:
    <<: *common-settings
    environment:
      - PATRONI_NAME=dbnode1
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode1
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode1:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode1:8008

  dbnode2:
    <<: *common-settings
    environment:
      - PATRONI_NAME=dbnode2
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode2
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode2:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode2:8008

  dbnode3:
    <<: *common-settings
    environment:
      - PATRONI_NAME=dbnode3
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode3
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode3:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode3:8008

networks:
  dbs:
    internal: true

configs:
  haproxy_cfg:
    file: ./config/haproxy.cfg
  etcd_cfg:
    file: ./config/etcd.sh

secrets:
  patroni.yml:
    file: ./patroni.yml
